# Ubuntu-absed server
FROM ubuntu:18.04
MAINTAINER Steve Jobbs <s.jobbs@mail.ru>
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:linuxuprising/java 
RUN apt-get update 
RUN apt install default-jdk -y
RUN mkdir /opt/distr
RUN apt install imagemagick -y
#libwebkitgtk-3.0-0 libjavascriptcoregtk-3.0-0 libMagickWand-6.Q16 libfreetype6 libgsf-1-114 libglib2.0-0 unixodbc libkrb5-3 libgssapi-krb5-2 -y
#ttf-mscorefonts-installer
#copying nescessary files
COPY example.distr1.txt /opt/distr
COPY example.distr2.txt /opt/distr
#setting environment variables
RUN export JAVA_HOME=/usr/lib/jvm/java-11-default-jdk-amd64
RUN export PATH=$PATH:$JAVA_HOME/bin
